name: Lint Code

on:
  push:
    paths:
      - 'bin/**/*.py'
      - 'tests/**/*.py'
  pull_request:
    paths:
      - 'bin/**/*.py'
      - 'tests/**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'
          cache-dependency-path: |
            bin/requirements.txt
            bin/requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bin/requirements-dev.txt

      - name: Run Ruff (Linter & isort)
        run: |
          ruff check bin/ltbox tests

      - name: Run Ruff (Formatter)
        run: |
          ruff format --check bin/ltbox tests

      - name: Run Mypy (Type Check)
        run: |
          mypy bin/ltbox tests --ignore-missing-imports
